Traceback (most recent call last):
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 604, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "d:\programs\anaconda\envs\py35\lib\site-packages\jupyter_client\asynchronous\channels.py", line 48, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\anaconda\envs\py35\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "d:\programs\anaconda\envs\py35\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 811, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 628, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "d:\programs\anaconda\envs\py35\lib\site-packages\nbclient\client.py", line 679, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
model.fit(
    X_train, y_train,
    batch_size=1024,
    epochs=30,
    verbose=1 # выводить информацию по ходу дела
);
-------------------

